name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1

    - name: Init submodule
      run: |
        git submodule update --init --recursive

    - name: Test MapReduce
      run: |
        sh map-reduce/test.sh
        
    - name: Test Rust
      run: cargo test

